name: app
description: It's your data. Take back control.
version: 0.4.0+1
publish_to: 'none'

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.10.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  amplitude_flutter: ^3.8.1
  firebase_core: ^1.15.0
  flutter_secure_storage: ^5.0.2
  intl_utils: ^2.6.1
  intl: ^0.17.0
  logging: ^1.0.2
  provider: ^6.0.2
  sentry_flutter: ^6.5.1
  sqflite_sqlcipher: ^2.1.0
  httpp: ^0.0.4
  tiki_decision: ^0.0.8
  tiki_wallet: ^0.0.16
  tiki_kv: ^0.1.1
  tiki_spam_cards: ^0.0.8
  tiki_user_account: ^0.0.5
  tiki_login: ^0.0.11
  tiki_money: ^0.0.8
  tiki_style: ^0.0.17
  tiki_data: ^0.0.6

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
  generate: true