name: app
description: It's your data. Take back control.
version: 0.3.1+1
publish_to: 'none'

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.10.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  amplitude_flutter: ^3.8.1
  android_intent: ^2.0.2
  carousel_slider: ^4.0.0
  data_connection_checker: ^0.3.4
  firebase_core: ^1.13.1
  flutter_appauth: ^2.4.1
  flutter_html: ^2.2.1
  flutter_lints: ^1.0.4
  flutter_markdown: ^0.6.9
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  intl_utils: ^2.6.1
  intl: ^0.17.0
  logging: ^1.0.2
  lottie: ^1.2.2
  path_provider: ^2.0.9
  permission_handler: ^8.3.0 # login for git compat
  provider: ^6.0.2
  sentry_flutter: ^6.3.0
  share_plus: ^3.1.0
  sizer: ^2.0.15
  sqflite_sqlcipher: ^2.1.0
  url_launcher: ^6.0.20
  user_account:
    path: ../user_account
  decision_sdk:
    path: ../decision_sdk
  wallet:
    git:
      url: https://github.com/tiki/wallet
      ref: 0.0.8
  httpp:
    git:
      url: https://github.com/tiki/httpp
      ref: 0.0.3
  login:
    git:
      url: https://github.com/tiki/login
      ref: 0.0.7
  google_provider:
    git:
      url: https://github.com/tiki/google_provider
      ref: 0.0.3
  microsoft_provider:
    git:
      url: https://github.com/tiki/microsoft_provider
      ref: 0.0.3
  money:
    git:
      url: https://github.com/tiki/money
      ref: 0.0.3

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - res/images/
    - res/animation/
    - res/json/
    - res/sql/
  fonts:
    - family: Koara
      fonts:
        - asset: res/fonts/Koara-Bold.ttf
          weight: 700
        - asset: res/fonts/Koara-Regular.ttf
        - asset: res/fonts/Koara-Light.ttf
          weight: 300
    - family: NunitoSans
      fonts:
        - asset: res/fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: res/fonts/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: res/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: res/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: res/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: res/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: res/fonts/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: res/fonts/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: res/fonts/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Medium.ttf
          weight: 500
    - family: SegoeUI
      fonts:
        - asset: res/fonts/Segoe-UI.ttf