name: app
description: It's your data. Take back control.
version: 0.4.2
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  amplitude_flutter: ^3.10.0
  firebase_core: ^1.18.0
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  logging: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sentry_flutter: ^6.6.1
  sqflite_sqlcipher: ^2.1.1
  httpp: ^0.0.5
  tiki_decision: ^0.0.13
  tiki_wallet: ^0.0.25
  tiki_kv: ^0.1.1
  tiki_spam_cards: ^0.0.10
  tiki_user_account: ^0.0.13
  tiki_login: ^0.0.15
  tiki_money: ^0.0.11
  tiki_style: ^0.0.20
  tiki_localgraph: ^0.0.7
  tiki_data: ^0.0.13

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override
  crypto: ^3.0.1 # for integration tests compatibility
  xml: ^5.0.0 # flutter_html in zendesk_flutter compatibility
  flutter_math_fork: ^0.6.3 # remove errors from console
  flutter_svg: ^1.0.0 # solve conflict between flutter_math_fork and flutter_html


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true